=== TripToRome/tiwm23tig05/src/comidas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="comidas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="comida" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="calorias" type="xs:integer"/>
              <xs:element name="preco" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== TripToRome/tiwm23tig05/src/comidas.xml
<comidas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="comidas.xsd">

  <comida>
    <nome>Carbonara</nome>
    <calorias>98</calorias>
    <preco>7€</preco>
  </comida>

  <comida>
    <nome>Pizza Romana</nome>
    <calorias>298</calorias>
    <preco>10€</preco>
  </comida>

  <comida>
    <nome>Supplì</nome>
    <calorias>229</calorias>
    <preco>1,50€</preco>
  </comida>

  <comida>
    <nome>Cacio e Pepe</nome>
    <calorias>211</calorias>
    <preco>5€</preco>
  </comida>

</comidas>

=== TripToRome/tiwm23tig05/comidas.xml
<comidas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="comidas.xsd">

  <comida>
    <nome>Carbonara</nome>
    <calorias>504</calorias>
    <preco>17</preco>
  </comida>

  <comida>
    <nome>Bolonhesa</nome>
    <calorias>600</calorias>
    <preco>15</preco>
  </comida>

  <comida>
    <nome>Pizza</nome>
    <calorias>266</calorias>
    <preco>10</preco>
  </comida>

</comidas>
